### ISSUE TITLE
Inline elements are rendered as block

### ISSUE THREAD

**Issue by paulmelnikow** [mapbox/react-click-to-select#12]
Hi, thanks for this library! I'm using it to build a new UI for https://github.com/badges/shields.

I'm wrapping an inline `input`:

```jsx
<p>
  Markdown&nbsp;
  <ClickToSelect>
    <input className="code" readOnly value={markdown} />
  </ClickToSelect>
</p>
```

Because it introduces a `div`, it's converting my inline element into a block element. Before:

<img width="619" alt="screen shot 2017-11-12 at 5 57 23 pm" src="https://user-images.githubusercontent.com/1487036/32704469-a4946bd6-c7d3-11e7-89e5-24b7a9d8d02d.png">

After:

<img width="520" alt="screen shot 2017-11-12 at 5 58 24 pm" src="https://user-images.githubusercontent.com/1487036/32704471-a9a004be-c7d3-11e7-9da5-f3e9da39f386.png">

The expected behavior is that `ClickToSelect` does not affect whether its contained elements are rendered inline or block. I could work around this behavior using CSS, but it seems better to fix it.

I can see three ways to do that:

1. Use a `span`
2. Let the user specify whether the contents are inline or block, and choose `span` or `div` accordingly
3. Try to infer from the children

After reading [this SO answer](https://stackoverflow.com/a/5545914/893113) I'm inclined to just use a `span`. What do you think?

**Comment by tristen** [comment]
Would adding a `display` prop work? DefaultProps value would be `block` otherwise a user could pass any valid CSS display value.

**Comment by paulmelnikow** [comment]
That sounds reasonable. I'll give it a try!

**Comment by paulmelnikow** [comment]
I get a React error when I do this:

```
validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
```

A [`<p>`](https://www.w3.org/TR/html5/grouping-content.html#the-p-element) is supposed to contain [phrasing content](https://www.w3.org/TR/html5/dom.html#phrasing-content-1), which a `<div>` is not. In HTML 4, this was also true. A `<p>` was not supposed to contain a `<div>`.

Given that monkey-wrench, I'd like to use a `span` here rather than a `div`, and let the caller pick which to use. What do you think?

**Comment by tristen** [comment]
> Given that monkey-wrench, I'd like to use a `span` here rather than a `div`, and let the caller pick which to use. What do you think?

Ah yeah, that sounds good to me.
